#!/usr/bin/env python3
import sys
import queue
import threading

import numpy as np
# TensorRT 8.5.x uses np.bool/np.int/np.float which were removed in NumPy 1.24.
# Patch before any tensorrt / ultralytics import.
np.bool   = bool
np.int    = int
np.float  = float
np.complex= complex
np.object = object
np.str    = str

import torch as _torch
import cv2
import rospy
from cv_bridge import CvBridge
from sensor_msgs.msg import Image, CompressedImage
from std_msgs.msg import String
from visualization_msgs.msg import Marker

SCOUT_PATH = "/home/zd/tracking_ws/src/Scout-Vision"
sys.path.insert(0, SCOUT_PATH)

from yolo_botsort import load_yolo_detector, get_best_detection
from box_utils import yolo_xywh_to_xyxy_pixels

# drone_tracking message — generated by catkin, available after build
from drone_tracking.msg import Detection


class DetectorNode:
    def __init__(self):
        rospy.init_node("detector_node", anonymous=False)

        engine_path    = rospy.get_param("~engine_path",
                             SCOUT_PATH + "/lrdd3_720_yolo26n.engine")
        image_topic    = rospy.get_param("~image_topic",
                             "/zedm/zed_node/left/image_rect_color")
        use_compressed = rospy.get_param("~use_compressed", True)
        self.conf      = rospy.get_param("~conf", 0.06)
        self.iou       = rospy.get_param("~iou", 0.50)
        self.class_id  = rospy.get_param("~class_id", 0)
        self.device    = rospy.get_param("~device", "cuda:0")
        self.tracker   = rospy.get_param("~tracker", "bytetrack.yaml")

        rospy.loginfo(f"[detector] Loading TRT engine: {engine_path}")
        self.detector = load_yolo_detector(engine_path, task="detect")
        self.detector.overrides['imgsz'] = 736

        # torchvision 0.16 egg was compiled against a different torch ABI.
        # Patch ops.nms NOW — after ultralytics is imported (it checks tv
        # metadata at import time) but before first inference (lazy import).
        import torchvision as _tv
        def _nms_pure(boxes, scores, iou_threshold):
            if boxes.numel() == 0:
                return _torch.empty(0, dtype=_torch.long)
            b = boxes.float().cpu(); s = scores.float().cpu()
            x1, y1, x2, y2 = b[:,0], b[:,1], b[:,2], b[:,3]
            areas = (x2-x1)*(y2-y1)
            order = s.argsort(descending=True); keep = []
            while order.numel() > 0:
                i = order[0].item(); keep.append(i)
                if order.numel() == 1: break
                rest = order[1:]
                inter = ((x2[rest].clamp(max=x2[i].item()) - x1[rest].clamp(min=x1[i].item())).clamp(0) *
                         (y2[rest].clamp(max=y2[i].item()) - y1[rest].clamp(min=y1[i].item())).clamp(0))
                iou = inter / (areas[i] + areas[rest] - inter + 1e-6)
                order = rest[iou <= iou_threshold]
            return _torch.tensor(keep, dtype=_torch.long)
        _tv.ops.nms = _nms_pure
        rospy.loginfo("[detector] torchvision NMS patched with pure-PyTorch fallback")

        dummy = np.zeros((736, 1280, 3), dtype=np.uint8)
        get_best_detection(self.detector, dummy,
                           self.conf, self.iou, self.class_id,
                           self.device, self.tracker, use_track=False)
        rospy.loginfo("[detector] Model ready.")

        self._target_id   = None  # sticky track ID; avoids jumping between overlapping detections
        self._target_miss = 0    # consecutive frames without detection before clearing _target_id

        self._jpeg_params = [int(cv2.IMWRITE_JPEG_QUALITY), 80]

        self.bridge = CvBridge()

        self.pub_det    = rospy.Publisher("~detection",                  Detection,       queue_size=5)
        self.pub_img    = rospy.Publisher("~annotated_image/compressed", CompressedImage, queue_size=1)
        self.pub_status = rospy.Publisher("~status",                     String,          queue_size=1)
        self.pub_marker = rospy.Publisher("~status_marker",              Marker,          queue_size=5)

        # Queue(maxsize=1): always hold the latest frame only
        self._q = queue.Queue(maxsize=1)

        if use_compressed:
            rospy.Subscriber(image_topic + "/compressed", CompressedImage,
                             self._compressed_cb, queue_size=1, buff_size=2**24)
        else:
            rospy.Subscriber(image_topic, Image,
                             self._image_cb, queue_size=1, buff_size=2**24)

        self._worker = threading.Thread(target=self._infer_loop, daemon=True)
        self._worker.start()
        rospy.loginfo("[detector] Node ready.")

    # ------------------------------------------------------------------
    # Image callbacks — must return as fast as possible
    # ------------------------------------------------------------------

    def _enqueue(self, frame, header):
        item = (frame, header)
        try:
            self._q.put_nowait(item)
        except queue.Full:
            try:
                self._q.get_nowait()
            except queue.Empty:
                pass
            self._q.put_nowait(item)

    def _compressed_cb(self, msg: CompressedImage):
        buf = np.frombuffer(msg.data, dtype=np.uint8)
        frame = cv2.imdecode(buf, cv2.IMREAD_COLOR)
        if frame is not None:
            self._enqueue(frame, msg.header)

    def _image_cb(self, msg: Image):
        try:
            frame = self.bridge.imgmsg_to_cv2(msg, "bgr8")
            self._enqueue(frame, msg.header)
        except Exception as e:
            rospy.logwarn_throttle(5.0, f"[detector] cv_bridge: {e}")

    # ------------------------------------------------------------------
    # Inference worker thread
    # ------------------------------------------------------------------
    def _infer_loop(self):

        recent_frames = []
        max_buffer_size = 5

        while not rospy.is_shutdown():
            try:
                frame, header = self._q.get(timeout=0.1)
            except queue.Empty:
                continue

            h, w = frame.shape[:2]

            box, _ = get_best_detection(
                self.detector, frame,
                self.conf, self.iou, self.class_id,
                self.device, self.tracker,
                use_track=True, preferred_id=self._target_id)

            det = Detection()
            det.header   = header
            # Outlier Identification
            is_outlier = False

            if box is not None and recent_frames:
                cx_curr, cy_curr = box.cx, box.cy

                last_f = recent_frames[-1]
                cx_last, cy_last = last_f['cx'], last_f['cy']
                
                # Euclidean distance
                center_dist = np.hypot(cx_curr - cx_last, cy_curr - cy_last)
                # Calculate diagonal of the previous B_box
                last_diag = np.hypot(last_f['w'], last_f['h'])
                # Outlier Criteria
                max_recent_conf = max(f['conf'] for f in recent_frames)

                if center_dist > (2 * last_diag) and box.conf <= max_recent_conf:
                    rospy.logwarn(f"[detector] Outlier detected! Jump of {center_dist:.2f}")
                    is_outlier = True

            if box is not None and not is_outlier:
                det.detected = True
                det.cx       = box.cx
                det.cy       = box.cy
                det.width    = box.w
                det.height   = box.h
                det.conf     = box.conf
                det.track_id = box.track_id if box.track_id is not None else -1
                det.error_x  = box.cx - 0.5

                self._target_id   = box.track_id
                self._target_miss = 0

                recent_frames.append({'cx': box.cx, 'cy': box.cy, 'w': box.w, 'h': box.h, 'conf': box.conf})
                if len(recent_frames) > max_buffer_size:
                    recent_frames.pop(0)
            else:
                det.detected = False
                self._target_miss += 1
                if self._target_miss >= 5: # ~0.5 s at 10 fps before abandoning locked ID
                    self._target_id   = None
                    self._target_miss = 0
                    recent_frames = []

            self.pub_det.publish(det)
            self.pub_status.publish(String(data="detected" if det.detected else "none"))

            if self.pub_img.get_num_connections() > 0:
                self._publish_annotated(frame, header, box if not is_outlier else None, w, h, det)

    def _publish_annotated(self, frame, header, box, w, h, det):
        annotated = frame.copy()
        cv2.line(annotated, (w // 2, 0), (w // 2, h), (255, 80, 0), 1)
        if box is not None:
            x1, y1, x2, y2 = yolo_xywh_to_xyxy_pixels(
                box.cx, box.cy, box.w, box.h, w, h)
            cv2.rectangle(annotated, (x1, y1), (x2, y2), (0, 255, 0), 2)
            label = f"ID:{det.track_id} {box.conf:.2f}"
            cv2.putText(annotated, label, (x1, max(y1 - 6, 10)),
                        cv2.FONT_HERSHEY_SIMPLEX, 0.5, (0, 255, 0), 1)
            cx_px = int(box.cx * w)
            cy_px = int(box.cy * h)
            cv2.drawMarker(annotated, (cx_px, cy_px), (0, 0, 255),
                           cv2.MARKER_CROSS, 16, 2)
            cv2.line(annotated, (w // 2, cy_px), (cx_px, cy_px), (0, 0, 255), 1)
        ok, buf = cv2.imencode(".jpg", annotated, self._jpeg_params)
        if ok:
            msg = CompressedImage()
            msg.header = header
            msg.format = "jpeg"
            msg.data   = buf.tobytes()
            self.pub_img.publish(msg)

    def _publish_marker(self, header, box, det):
        m = Marker()
        m.header          = header
        m.header.frame_id = "base_link"
        m.ns              = "detection_status"
        m.id              = 0
        m.type            = Marker.TEXT_VIEW_FACING
        m.action          = Marker.ADD
        m.pose.orientation.w = 1.0
        m.pose.position.z    = 1.5
        m.scale.z            = 0.15
        m.lifetime           = rospy.Duration(0.4)
        if box is not None:
            m.color.r, m.color.g, m.color.b, m.color.a = 0.0, 1.0, 0.0, 1.0
            m.text = f"TRACKING  ID:{det.track_id}  conf:{box.conf:.2f}  err_x:{det.error_x:+.3f}"
        else:
            m.color.r, m.color.g, m.color.b, m.color.a = 1.0, 0.4, 0.0, 1.0
            m.text = "NO DETECTION"
        self.pub_marker.publish(m)

    def spin(self):
        rospy.spin()


if __name__ == "__main__":
    DetectorNode().spin()
