// Generated by gencpp from file drone_tracking/Detection.msg
// DO NOT EDIT!


#ifndef DRONE_TRACKING_MESSAGE_DETECTION_H
#define DRONE_TRACKING_MESSAGE_DETECTION_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace drone_tracking
{
template <class ContainerAllocator>
struct Detection_
{
  typedef Detection_<ContainerAllocator> Type;

  Detection_()
    : header()
    , detected(false)
    , cx(0.0)
    , cy(0.0)
    , width(0.0)
    , height(0.0)
    , conf(0.0)
    , track_id(0)
    , error_x(0.0)  {
    }
  Detection_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , detected(false)
    , cx(0.0)
    , cy(0.0)
    , width(0.0)
    , height(0.0)
    , conf(0.0)
    , track_id(0)
    , error_x(0.0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef uint8_t _detected_type;
  _detected_type detected;

   typedef float _cx_type;
  _cx_type cx;

   typedef float _cy_type;
  _cy_type cy;

   typedef float _width_type;
  _width_type width;

   typedef float _height_type;
  _height_type height;

   typedef float _conf_type;
  _conf_type conf;

   typedef int32_t _track_id_type;
  _track_id_type track_id;

   typedef float _error_x_type;
  _error_x_type error_x;





  typedef boost::shared_ptr< ::drone_tracking::Detection_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::drone_tracking::Detection_<ContainerAllocator> const> ConstPtr;

}; // struct Detection_

typedef ::drone_tracking::Detection_<std::allocator<void> > Detection;

typedef boost::shared_ptr< ::drone_tracking::Detection > DetectionPtr;
typedef boost::shared_ptr< ::drone_tracking::Detection const> DetectionConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::drone_tracking::Detection_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::drone_tracking::Detection_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::drone_tracking::Detection_<ContainerAllocator1> & lhs, const ::drone_tracking::Detection_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.detected == rhs.detected &&
    lhs.cx == rhs.cx &&
    lhs.cy == rhs.cy &&
    lhs.width == rhs.width &&
    lhs.height == rhs.height &&
    lhs.conf == rhs.conf &&
    lhs.track_id == rhs.track_id &&
    lhs.error_x == rhs.error_x;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::drone_tracking::Detection_<ContainerAllocator1> & lhs, const ::drone_tracking::Detection_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace drone_tracking

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::drone_tracking::Detection_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::drone_tracking::Detection_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::drone_tracking::Detection_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::drone_tracking::Detection_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::drone_tracking::Detection_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::drone_tracking::Detection_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::drone_tracking::Detection_<ContainerAllocator> >
{
  static const char* value()
  {
    return "3596dd143859f8f7cb18a2f97daa2146";
  }

  static const char* value(const ::drone_tracking::Detection_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x3596dd143859f8f7ULL;
  static const uint64_t static_value2 = 0xcb18a2f97daa2146ULL;
};

template<class ContainerAllocator>
struct DataType< ::drone_tracking::Detection_<ContainerAllocator> >
{
  static const char* value()
  {
    return "drone_tracking/Detection";
  }

  static const char* value(const ::drone_tracking::Detection_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::drone_tracking::Detection_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Header header\n"
"bool    detected\n"
"float32 cx\n"
"float32 cy\n"
"float32 width\n"
"float32 height\n"
"float32 conf\n"
"int32   track_id\n"
"float32 error_x\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::drone_tracking::Detection_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::drone_tracking::Detection_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.detected);
      stream.next(m.cx);
      stream.next(m.cy);
      stream.next(m.width);
      stream.next(m.height);
      stream.next(m.conf);
      stream.next(m.track_id);
      stream.next(m.error_x);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Detection_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::drone_tracking::Detection_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::drone_tracking::Detection_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "header: ";
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "detected: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.detected);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "cx: ";
    Printer<float>::stream(s, indent + "  ", v.cx);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "cy: ";
    Printer<float>::stream(s, indent + "  ", v.cy);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "width: ";
    Printer<float>::stream(s, indent + "  ", v.width);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "height: ";
    Printer<float>::stream(s, indent + "  ", v.height);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "conf: ";
    Printer<float>::stream(s, indent + "  ", v.conf);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "track_id: ";
    Printer<int32_t>::stream(s, indent + "  ", v.track_id);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "error_x: ";
    Printer<float>::stream(s, indent + "  ", v.error_x);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DRONE_TRACKING_MESSAGE_DETECTION_H
